# Generated by Django 4.0.3 on 2022-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0008_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
