# Generated by Django 4.0.3 on 2022-04-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
